name: Tests
on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Unit Tests
        run: yarn test --watchAll=false

  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start App
        run: |
          yarn
          NODE_ENV=test yarn build
          NODE_ENV=test yarn start &

      - name: Run E2E
        run: |
          yarn cypress:headless
